<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Driftwood.Tools.IconForge</RootNamespace>
    <AssemblyName>IconForge</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Driftwood.Core\Driftwood.Core.csproj" />
  </ItemGroup>

</Project>
